### ISSUE TITLE
Issues on checker rules

### ISSUE THREAD

**Issue by brijq** [cosmos/b9-checkers-academy-draft#23]
On file full_game.go understand there is an import dependency on 

"github.com/xavierlepretre/checkers/x/checkers/rules"

line 6 of the file,

Is that still available? As I am trying to learn and build with this checker example.

Please assist.

**Comment by xavierlepretre** [comment]
You are talking about [here](https://github.com/cosmos/b9-checkers-academy-draft/blob/3c69e22/x/checkers/types/full_game.go#L6), right?
Although it looks like an external import, it is actually a reference to this file, which is part of the repo: https://github.com/cosmos/b9-checkers-academy-draft/blob/3c69e2251f253288163021c75999709d8c25b402/x/checkers/rules/checkers.go

**Comment by brijq** [comment]
Yes correct. Thank you for your prompt response, got it. 

Thank you so much
