### ISSUE TITLE
Missing x/checkers/types/full_game.go 

### ISSUE THREAD

**Issue by GeorgeGkinis** [cosmos/b9-checkers-academy-draft#25]
I followed [all steps](https://tutorials.cosmos.network/academy/4-my-own-chain/stored-game.html) carefully up to here : **starport scaffold map storedGame game turn red black --module checkers --no-message**

Afterwards the file **full_game.go** is mentioned but does not exists on my fs.

Did I miss anything?

**Comment by xavierlepretre** [comment]
That's right. This `full_game.go` is a file you create yourself. And you add the helper functions in it.
