### ISSUE TITLE
Repo being mentioned no longer exists. 

### ISSUE THREAD

**Issue by mdulin2** [cosmos/b9-checkers-academy-draft#46]
A [repo](https://github.com/cosmos/b9-checkers-academy-draft/blob/full-game-object/x/checkers/types/full_game.go#L7) being mentioned for imports no longer exists. Clearly, this breaks the build process.

**Comment by mdulin2** [comment]
I'm new to Go and understand what happened now. I thought that the 'github.com/....' was pointing to a Github repo. In reality, the NAME of the module is that. 

In the example, we're naming the module 'github.com/alice...'. It may be worth keeping this the same as the demo, especially for those new to Go, like myself.

**Comment by xavierlepretre** [comment]
Indeed.
There is the name used in this repo `github.com/b9lab` and the name used in the samples of the educational content: `github.com/alice`.
If you start copy-pasting the full file, this is what happens.
