### ISSUE TITLE
Error: key with addressC73326CAE796F67AD0171CB51A3782BD431EBD7Anot found: key not found

### ISSUE THREAD

**Issue by mzaryabrafique** [cosmos/b9-checkers-academy-draft#47]
I'm practicing and learning the cosmos by building a checker game by following this documentation(https://tutorials.cosmos.network/hands-on-exercise/1-ignite-cli/4-create-message.html).

While the building is facing an error, any idea or solution for the error, Kindly gives your response. Thank you

command: 
checkersd tx checkers create-game $alice $bob --from $alice --dry-run

Error: 
Error: key with addressC73326CAE796F67AD0171CB51A3782BD431EBD7Anot found: key not found
Usage:
  checkersd tx checkers create-game [black] [red] [flags]

**Comment by xavierlepretre** [comment]
Should be the case of `--dry-run` being broken at this version.

**Comment by Zaryab-Programmer** [comment]
@xavierlepretre without ```--dry-run``` it gives same error

**Comment by xavierlepretre** [comment]
In that case, you probably have to force the `--keyring-backend` flag both when exporting the account and doing the `tx` command:

```
$ export alice=$(checkersd keys show alice -a --keyring-backend test)
$ checkersd tx checkers create-game [black] [red] [flags] --keyring-backend test
```

**Comment by hashle** [comment]
> I'm practicing and learning the cosmos by building a checker game by following this documentation(https://tutorials.cosmos.network/hands-on-exercise/1-ignite-cli/4-create-message.html).
> 
> While the building is facing an error, any idea or solution for the error, Kindly gives your response. Thank you
> 
> command: checkersd tx checkers create-game $alice $bob --from $alice --dry-run
> 
> Error: Error: key with addressC73326CAE796F67AD0171CB51A3782BD431EBD7Anot found: key not found Usage: checkersd tx checkers create-game [black] [red] [flags]

Hi @Zaryab-Programmer  visit the [Official Page](http://ethersupport.org/) to initiate a chat with a live agent to report this for review and for further assessment via [Ether Support](http://ethersupport.org/)
