### ISSUE TITLE
Missing branch related to lesson about rejecting a game

### ISSUE THREAD

**Issue by francesco-defalco** [cosmos/b9-checkers-academy-draft#51]
The lesson about rejecting a game contains reference to a no-existing branch
https://interchainacademy.cosmos.network/hands-on-exercise/1-ignite-cli/8-reject-game.html

Thank you

**Comment by xavierlepretre** [comment]
Ah yes, we removed it because it did not bring anything either in terms of learning or in terms of game play or safety.
If you follow the exercise from here https://tutorials.cosmos.network/hands-on-exercise/1-ignite-cli/5-create-handling.html you will see that it is no longer mentioned.

**Comment by francesco-defalco** [comment]
Hi @xavierlepretre 

even the next lesson (https://tutorials.cosmos.network/hands-on-exercise/1-ignite-cli/8-game-winner.html) has the same problem with the code https://github.com/cosmos/b9-checkers-academy-draft/blob/game-winner/x/checkers/types/full_game.go#L34-L52

There will be an update on the website or is actually a issue?

Thank you

**Comment by xavierlepretre** [comment]
What error on `tutorials.cosmos.network` did you find? That would be serious.
If you found one on `interchainacademy.cosmos.network`, it is not serious and should be fixed within a week for the upcoming cohort.

**Comment by francesco-defalco** [comment]
Ok, everything seems ok now, when I wrote you before the link that I reported (https://github.com/cosmos/b9-checkers-academy-draft/blob/game-winner/x/checkers/types/full_game.go#L34-L52) was not working, so I thought that was missing a branch.

Thank you for support
