### ISSUE TITLE
Rules repository does not seem to exist so the unit test fails

### ISSUE THREAD

**Issue by daveicm** [cosmos/b9-checkers-academy-draft#55]
Turorial code at `x/checkers/types/full_game.go`:

import: 

`"github.com/b9lab/checkers/x/checkers/rules"`

the repository doesn't seem to exist, returns 404 so the unit test does not PASS

**Comment by xavierlepretre** [comment]
**You** copy the file as described [here](https://tutorials.cosmos.network/hands-on-exercise/1-ignite-cli/3-stored-game.html#defining-the-rule-set).

And you replace `github.com/b9lab/checkers/` with whichever name you gave to your package.

**Comment by daveicm** [comment]
i think i am missing something because 

i added the import line like this: 
"x/checkers/rules" 

 now get the folloing error:

x/checkers/types/full_game.go:6:2: package x/checkers/rules is not in GOROOT (/usr/local/go/src/x/checkers/rules)

**Comment by xavierlepretre** [comment]
Do you have a `x/checkers` folder in the checkers project?
Not the Go root.

**Comment by daveicm** [comment]
yes there is the file checkers.go in path x/checkers/rules/checkers.go

**Comment by xavierlepretre** [comment]
And what package name did you give to your checkers project?
If you are unsure, that's the first line in `go.mod`.

**Comment by daveicm** [comment]
ok i see the problem now and passed the first unit test. 

The import line should have the complete package name as it was given [Here](https://tutorials.cosmos.network/hands-on-exercise/1-ignite-cli/1-ignitecli.html#your-chain)

"github.com/alice/checkers/x/checkers/keeper" 

i think it is a little bit confusing for new comers since on the [Additional helper functions](https://tutorials.cosmos.network/hands-on-exercise/1-ignite-cli/3-stored-game.html#additional-helper-functions) section does not state that you have to import it with the name we provided [above](https://tutorials.cosmos.network/hands-on-exercise/1-ignite-cli/1-ignitecli.html#your-chain) 

we just need to change the b9lab to alice or whatever name we gave to the package

**Comment by xavierlepretre** [comment]
If you use VSCode, usually if the cursor is on a red-underlined text, a `CTRL-.` or `CMD-.` will have the IDE suggest to you the right import.
