### ISSUE TITLE
Redundant check condition

### ISSUE THREAD

**Issue by ThanhNhann** [cosmos/b9-checkers-academy-draft#57]
I see that `MustRefundWager` function checks [three conditions](https://github.com/cosmos/b9-checkers-academy-draft/blob/bad638ae7e867c72331241b4aebf7769d59f9e04/x/checkers/keeper/wager_handler.go#L56) with `MoveCount` but when we use it at `EndBlocker`, it just checks the case `MoveCount == 1` and then calls `MustRefundWager` [here](https://github.com/cosmos/b9-checkers-academy-draft/blob/dd74039c70dc9079b8d2b51c6628216f38c7329f/x/checkers/keeper/end_block_server_game.go#L48), so it will always point in one case in `MustRefundWager` function and will never go to another cases like `MoveCount == 0`

**Comment by xavierlepretre** [comment]
Yes. `MustRefundWager` exists and should cover all situations, regardless of how it is being used.

The fix I see is that `EndBlocker` does not need to make the extra check for `== 1` because `== 0` is a valid situation.

I will include that in a future revision of the code.
