### ISSUE TITLE
Error on building docker: https://tutorials.cosmos.network/hands-on-exercise/4-run-in-prod/1-run-prod-docker.html

### ISSUE THREAD

**Issue by perfogic** [cosmos/b9-checkers-academy-draft#60]
Hello, I failed at this command after building dockerfile:
![image](https://github.com/cosmos/b9-checkers-academy-draft/assets/74671798/31b1f400-6c2e-4c70-89a4-502377b6d1a7)

Is there anyway to fix it ? Thank you:
![image](https://github.com/cosmos/b9-checkers-academy-draft/assets/74671798/7dde8ca5-d603-441c-a960-1b37bb9c8129)
![image](https://github.com/cosmos/b9-checkers-academy-draft/assets/74671798/0c774f72-adc9-4594-b42a-f90451f1883e)

**Comment by perfogic** [comment]
Fixed with debian:latest, but i willl leave it here for you to confirm whether it is okay when i update debian version to latest

**Comment by perfogic** [comment]
I face other eror when do command, can you help me why also ? thank you:
Here i can't read client.toml, node_key.json, pri_validator_key.json
![image](https://github.com/cosmos/b9-checkers-academy-draft/assets/74671798/ca6a03e5-3d88-4d3e-9078-e00b91995d53)
Here is the command i run:
![image](https://github.com/cosmos/b9-checkers-academy-draft/assets/74671798/c290b094-9c9a-4264-9b3c-87460b59cff4)

**Comment by perfogic** [comment]
@xavierlepretre hello, can you check it out ?

**Comment by xavierlepretre** [comment]
The content uses `alpine` for both compilation and production, right? You switched to `debian` for (only) production as an experimentation, right? Did you make sure that the compilation step uses `CGO_ENABLED=0`?

And if you do `cat client.toml`, do you get anything? 
I hope you did **not** run the `make` commands with `sudo`.
