### ISSUE TITLE
Need help on https://tutorials.cosmos.network/hands-on-exercise/4-run-in-prod/2-migration-info.html

### ISSUE THREAD

**Issue by perfogic** [cosmos/b9-checkers-academy-draft#61]
Hello, i have to skip through docker simulation lecture and jump to [tally ](https://tutorials.cosmos.network/hands-on-exercise/4-run-in-prod/2-migration-info.html)
However, after doing it i face error on integration tests.
![image](https://github.com/cosmos/b9-checkers-academy-draft/assets/74671798/5c851704-8259-4b07-ad9e-51d687ee03c4)

Is there anyways to fix this ? Thank you. Here is my code: https://github.com/perfogic/cosmos-checkers/tree/feature/continue-without-docker

**Comment by perfogic** [comment]
Other infor for this: that i realize on my app, it have monitoring module and maybe this lead to error but i donn't know how to fix it properly.

**Comment by xavierlepretre** [comment]
Yes, there is this text on the page:

> Be aware that the monitoring module added by Ignite causes difficulty when experimenting below with the CLI. To keep things simple, remove [all references to monitoring (opens new window)](https://github.com/cosmos/b9-checkers-academy-draft/compare/player-info-handling..player-info-migration#diff-0f1d2976054440336a576d47a44a37b80cdf6701dd9113012bce0e3c425819b7L159) from app.go.

And in the link, you can see how all references are removed.
