### ISSUE TITLE
Possible bad link on 6-play-game step on testing message

### ISSUE THREAD

**Issue by apollo-pablo** [cosmos/b9-checkers-academy-draft#63]
On the guide:

[6-play-game](https://tutorials.cosmos.network/hands-on-exercise/1-ignite-cli/6-play-game.html)

on 
[on-the-message](https://tutorials.cosmos.network/hands-on-exercise/1-ignite-cli/6-play-game.html#on-the-message)

When:

**Then adjust and add to the test cases:**

The link to code points to **msg_server_play_move_test.go** instead of **message_play_move_test.go**.

**Comment by xavierlepretre** [comment]
Good catch. Fixing it.
